### ISSUE TITLE
building from source

### ISSUE THREAD

**Issue by alexmyczko** [Laidout/laidout#14]
freetype-config does not exist anymore:

https://metadata.ftp-master.debian.org/changelogs//main/f/freetype/freetype_2.9.1-3_changelog

can you switch to pkg-config ?

**Comment by tomlechner** [comment]
Ack, thought I mostly fixed that in master! Hmm.. Checked more thoroughly this time. Should be fixed now in master. 
If someone were to help me get Laidout into the Debian repository, I can put together a new release version with this fix if desired. Just saying!

**Comment by alexmyczko** [comment]
Still fails without finding freetype, ah but that's lax!
/usr/include/X11/Xft/Xft.h:39:10: fatal error: ft2build.h: No such file or directory  
http://phd-sid.ethz.ch/debian/laidout/master/laidout_0.097%2Bgit20181221-1_amd64.build
http://phd-sid.ethz.ch/debian/laidout/master/laxkit_0.0.8.1_amd64.build

**Comment by tomlechner** [comment]
Aaaa.. so many compiler warnings suddenly with new g++!! As time goes on, g++ complains about the dumbest things sometimes.

Speaking of dumb things, I guess I might have broken master for the moment.. Sorry about that, I usually try to have master at least compilable. A workaround that should work is to pass in "--disable-graphics-magick" to the Laxkit configure.

I'm in the middle of some drastic changes, such as replacing really old Xft and Imlib dependencies with GraphicsMagick based image loading, but running into some irritating GraphicsMagick related compile errors (on sid).

**Comment by tomlechner** [comment]
Ok, might have gotten Laidout (and laxkit) compilable again right out of the repo with default configure, which has the brand new GraphicsMagick stuff turned off by default. Cleared most of the new compiler warnings except for harfbuzz related warnings.

Currently in Sid, for me anyway, there appears to be GraphicsMagick include file bug saying ‘MagickLib::ZSTDCompression’ and ‘MagickLib::WebPCompression’ have not been declared. If I comment out those lines in:
   /usr/include/GraphicsMagick/Magick++/Include.h
then I can compile again.

**Comment by tomlechner** [comment]
Assuming this is resolved.
